# pulseheights_cut_x1, counts_cut_x1 = adjust(pulseheights_x1, counts_total_x1)
# pulseheights_cut_x2, counts_cut_x2 = adjust(pulseheights_x2, counts_total_x2)
# pulseheights_cut_x3, counts_cut_x3 = adjust(pulseheights_x3, counts_total_x3)
# pulseheights_cut_x4, counts_cut_x4 = adjust(pulseheights_x4, counts_total_x4)
# pulseheights_cut_x5, counts_cut_x5 = adjust(pulseheights_x5, counts_total_x5)
# pulseheights_cut_no_source, counts_cut_no_source = adjust(pulseheights_background, counts_tot_background)

# plt.plot(pulseheights_cut_x1, counts_cut_x1, color = 'blue', label = "x = 1.5 cm")
# plt.plot(pulseheights_cut_x2, counts_cut_x2, color = 'green', label = "x = 4.5 cm")
# plt.plot(pulseheights_cut_x3, counts_cut_x3, color = 'purple', label = "x = 7.5 cm")
# plt.plot(pulseheights_cut_x4, counts_cut_x4, color = 'yellow', label = "x = 10.5 cm")
# plt.plot(pulseheights_cut_x5, counts_cut_x5, color = 'black', label = "x = 13.5 cm")
# plt.plot(pulseheights_cut_no_source, counts_cut_no_source, color = 'red', label = 'background')
# plt.gca().set_facecolor('lightgrey')
# plt.title("measurements with box filtered to peak")
# plt.legend(loc = 'upper right')
# plt.xlim(150, 300)
# plt.ylabel("counts")
# plt.xlabel("pulseheights (mV)")
# plt.show()




# plt.plot(pulseheights_x1, counts_total_x1, color = 'blue', label = "x = 1.5 cm")
# plt.plot(pulseheights_x2, counts_total_x2, color = 'green', label = "x = 4.5 cm")
# plt.plot(pulseheights_x3, counts_total_x3, color = 'purple', label = "x = 7.5 cm")
# plt.plot(pulseheights_x4, counts_total_x4, color = 'yellow', label = "x = 10.5 cm")
# plt.plot(pulseheights_x5, counts_total_x5, color = 'black', label = "x = 13.5 cm")
# plt.plot(pulseheights_background, counts_tot_background, color = 'red', label = 'background')
# plt.gca().set_facecolor('lightgrey')
# plt.title("measurements with box")
# plt.legend(loc = 'upper right')
# plt.xlim(0, 750)
# plt.ylabel("counts")
# plt.xlabel("pulseheights (mV)")
# plt.show()